---
# tasks file for Get-GitHub-Repository
  
  -
     name: Create Directory
     file:
      path: "{{ SRC_INSTALL }}"
      state: directory
  -
     name: Git clone repository
     git:
       repo: '{{PROTOCOL}}://{{ FQDN }}/{{ SUB_FOLDER }}'
       dest: "{{ SRC_INSTALL }}"
       version: master
       clone: yes
       update: yes
       force: 
