---
# tasks file for Get-GitHub-Repository
  -
     name: Git clone repository
     git:
       repo: '{{PROTOCOL}}://{{ FQDN }}/{{ SUB_FOLDER }}'
       dest: "{{ SRC_INSTALL }}"
       version: master
       clone: yes
       update: yes
       force: yes
